#
# Configuration file to create conda environment to run ITSCube related code.
#
# To create conda environment, run command:
#
# $ conda env create -f cube_environment.yml
#
# Followed by the following command to activate the environment:
#
# $ conda activate itscube
#
name: itscube

channels:
- conda-forge

dependencies:
- python=3.8
- joblib
- matplotlib-base
- dask
- pandas
- shapely
- h5py
- h5netcdf
- requests
- pyproj
- xarray
- netcdf4
- flake8
- nodejs
# - jupyterlab
# - jupyter_contrib_nbextensions
# - jupyter_nbextensions_configurator
# - ipyleaflet
- s3fs
- tqdm
- utm
- zarr
- gdal
- pip
# - pip:
#   - area
#   - git+git://github.com/icesat2py/icepyx@development
#   - python-cmr
