#
# Configuration file to create conda environment to run ItsLiveCube related code.
#
# To create conda environment, run command:
#
# $ conda env create -f cube_environment.yml
#
# Followed by the following command to activate the environment:
#
# $ conda activate itslivecube
#
name: itslivecube

channels:
  - conda-forge

# Add accelleration packages for xarray (does not seem to make any
# difference at runtime):
# conda install -c conda-forge scipy bottleneck
dependencies:
  - python==3.9.6
  - dask==2.30.0
  - pandas
  - numpy
  - h5py
  - h5netcdf
  - requests
  - pyproj
  - xarray==0.20.1
  - netcdf4
  - flake8
  - s3fs==0.4.2
  - fsspec==0.8.3
  - tqdm
  - utm
  - zarr==2.6.1
  - pip
  - pip:
    - geojson
    - awscliv2
