#
# Configuration file to create conda environment to run ItsLiveCube related code.
#
# To create conda environment, run command:
#
# $ conda env create -f cube_environment.yml
#
# Followed by the following command to activate the environment:
#
# $ conda activate itslivecube
#
name: itslivecube

channels:
  - conda-forge

dependencies:
  - python==3.9.6
  - dask
  - pandas
  - numpy
  - h5py
  - h5netcdf
  - requests
  - pyproj
  - xarray
  - netcdf4
  - flake8
  - s3fs==0.4.2
  - fsspec==0.8.3
  - tqdm
  - utm
  - zarr
  - pip
  - pip:
    - geojson
    - awscli
