name: itsliveReproject
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=1.2.2
  - aiohttp=3.7.4
  - aioitertools=0.7.1
  - async-timeout=3.0.1
  - attrs=20.3.0
  - bokeh=2.3.1
  - boost-cpp=1.74.0
  - botocore=1.19.52
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - cfitsio=3.470
  - cftime=1.4.1
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - curl=7.76.0
  - cytoolz=0.11.0
  - dask=2021.4.0
  - dask-core=2021.4.0
  - distributed=2021.4.0
  - expat=2.3.0
  - flake8=3.9.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=0.9.0
  - gdal=3.2.2
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - h5netcdf=0.10.0
  - h5py=3.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=68.1
  - idna=3.1
  - importlib-metadata=3.10.1
  - jinja2=2.11.3
  - jmespath=0.10.0
  - jpeg=9d
  - json-c=0.15
  - kealib=1.4.14
  - krb5=1.17.2
  - lcms2=2.12
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.76.0
  - libcxx=11.1.0
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgdal=3.2.2
  - libglib=2.68.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=13.1
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - llvm-openmp=11.1.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - ncurses=6.2
  - netcdf4=1.5.6
  - numpy=1.20.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - partd=1.2.0
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.10
  - postgresql=13.1
  - proj=8.0.0
  - psutil=5.8.0
  - pycodestyle=2.7.0
  - pycparser=2.20
  - pyflakes=2.3.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - s3fs=0.6.0
  - setuptools=49.6.0
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.35.4
  - tblib=1.7.0
  - tiledb=2.2.7
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.60.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2021a
  - tzdata=2021a
  - urllib3=1.26.4
  - wheel=0.36.2
  - wrapt=1.12.1
  - xarray=0.17.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zict=2.0.0
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - geojson==2.5.0
    - pyproj==3.0.1
    - scipy==1.6.2
