name: osx_itscube
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=1.2.0
  - aiohttp=3.7.3
  - aioitertools=0.7.1
  - argon2-cffi=20.1.0
  - asciitree=0.3.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0=mkl
  - bleach=3.2.1
  - bokeh=2.2.3=py38_0
  - botocore=1.19.57
  - branca=0.3.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - cached-property=1.5.2
  - certifi=2020.12.5
  - cffi=1.14.3
  - cftime=1.3.1
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.30.1
  - docutils=0.15.2
  - entrypoints=0.3
  - fasteners=0.16
  - flake8=3.8.4
  - freetype=2.10.4
  - fsspec=0.8.3
  - geos=3.8.1
  - h5netcdf=0.8.1
  - h5py=3.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - icu=67.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipyleaflet=0.13.3
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - json5=0.9.5
  - jsonschema=3.2.0
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lcms2=2.11
  - libcurl=7.71.1
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgfortran5=9.3.0
  - libiconv=1.16
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libuv=1.40.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - llvm-openmp=10.0.0
  - locket=0.2.1
  - lxml=4.6.1
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - monotonic=1.5
  - msgpack-python=1.0.1
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - netcdf4=1.5.4
  - nodejs=14.14.0
  - notebook=6.1.6
  - numcodecs=0.7.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.4
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.1
  - partd=1.1.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.2.4
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - psutil=5.7.2
  - ptyprocess=0.7.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pyflakes=2.2.0
  - pygments=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.5
  - pyyaml=5.4
  - pyzmq=20.0.0
  - readline=8.0
  - requests=2.24.0
  - s3fs=0.5.2
  - send2trash=1.5.0
  - setuptools=51.3.3
  - shapely=1.7.1
  - six=1.15.0
  - sortedcontainers=2.3.0
  - sqlite=3.33.0
  - tblib=1.7.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.52.0
  - traitlets=5.0.5
  - traittypes=0.2.1
  - urllib3=1.25.11
  - utm=0.6.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xarray=0.16.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zarr=2.6.1
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - appdirs==1.4.4
    - area==1.1.1
    - cfgv==3.2.0
    - click-plugins==1.1.1
    - cligj==0.7.0
    - datetime==4.3
    - distlib==0.3.1
    - filelock==3.0.12
    - fiona==1.8.17
    - geopandas==0.8.1
    - icepyx==0.3.0
    - identify==1.5.9
    - munch==2.5.0
    - nodeenv==1.5.0
    - pre-commit==2.8.2
    - python-cmr==0.4.1
    - toml==0.10.2
    - virtualenv==20.1.0
    - zope-interface==5.2.0
