#
# Configuration file to create conda environment to run ITS_LIVE granule
# reprojection code.
#
# To create conda environment, run command:
#
# $ conda env create -f reproject_environment.yml
#
# Followed by the following command to activate the environment:
#
# $ conda activate itsliveReproject
#
name: itsliveReproject

channels:
- conda-forge

dependencies:
- python=3.8
- dask
- h5py
- h5netcdf
- netcdf4
- xarray
- flake8
- s3fs
- tqdm
- gdal
- pip
- pip:
  - scipy
  - geojson
  - pyproj
